03-06-2019 23:18:02 ERROR143-Exception occured
org.springframework.dao.InvalidDataAccessApiUsageException: 5 parameters were supplied, but 7 in parameters were declared in class [com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameterCount(RdbmsOperation.java:444)
	at org.springframework.jdbc.object.RdbmsOperation.validateParameters(RdbmsOperation.java:405)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:136)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:117)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:200)
03-06-2019 23:18:30 ERROR143-Exception occured
org.springframework.dao.InvalidDataAccessApiUsageException: 5 parameters were supplied, but 7 in parameters were declared in class [com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameterCount(RdbmsOperation.java:444)
	at org.springframework.jdbc.object.RdbmsOperation.validateParameters(RdbmsOperation.java:405)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:136)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:117)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:200)
03-06-2019 23:20:35 ERROR144-Exception occured
org.springframework.dao.InvalidDataAccessApiUsageException: 5 parameters were supplied, but 7 in parameters were declared in class [com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameterCount(RdbmsOperation.java:444)
	at org.springframework.jdbc.object.RdbmsOperation.validateParameters(RdbmsOperation.java:405)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:136)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:117)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:201)
03-06-2019 23:24:10 ERROR144-Exception occured
org.springframework.dao.InvalidDataAccessApiUsageException: 5 parameters were supplied, but 7 in parameters were declared in class [com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl]
	at org.springframework.jdbc.object.RdbmsOperation.validateParameterCount(RdbmsOperation.java:444)
	at org.springframework.jdbc.object.RdbmsOperation.validateParameters(RdbmsOperation.java:405)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:136)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:117)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:201)
03-06-2019 23:30:27 ERROR147-Exception occured
org.springframework.dao.InvalidDataAccessApiUsageException: Required input parameter 'MOB_NUMBER' is missing
	at org.springframework.jdbc.core.CallableStatementCreatorFactory$CallableStatementCreatorImpl.createCallableStatement(CallableStatementCreatorFactory.java:207)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1090)
	at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1146)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:137)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:120)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:204)
03-06-2019 23:31:17 ERROR147-Exception occured
org.springframework.dao.DataIntegrityViolationException: CallableStatementCallback; SQL [{call GET_ENROLLMENT(?, ?, ?, ?, ?, ?, ?, ?, ?)}]; Data truncation: Data too long for column 'CVVNO' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'CVVNO' at row 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1107)
	at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1146)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:137)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:120)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:204)
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'CVVNO' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:387)
	at com.mysql.cj.jdbc.CallableStatement.execute(CallableStatement.java:842)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$call$4(JdbcTemplate.java:1147)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1092)
	... 4 more
03-06-2019 23:33:27 ERROR147-Exception occured
org.springframework.dao.DataIntegrityViolationException: CallableStatementCallback; SQL [{call GET_ENROLLMENT(?, ?, ?, ?, ?, ?, ?, ?, ?)}]; Data truncation: Data too long for column 'CVVNO' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'CVVNO' at row 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1107)
	at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1146)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:137)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:120)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:204)
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'CVVNO' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:387)
	at com.mysql.cj.jdbc.CallableStatement.execute(CallableStatement.java:842)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$call$4(JdbcTemplate.java:1147)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1092)
	... 4 more
03-06-2019 23:35:46 ERROR141-Exception caught
com.tesco.card.payments.exceptions.BusinessException
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:134)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:204)
04-06-2019 10:32:24 ERROR143-Exception caught
com.tesco.card.payments.exceptions.BusinessException
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:136)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:207)
04-06-2019 10:33:00 ERROR149-Exception occured
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLSyntaxErrorException: Unknown database 'bpa/prod'
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1087)
	at org.springframework.jdbc.core.JdbcTemplate.call(JdbcTemplate.java:1146)
	at org.springframework.jdbc.object.StoredProcedure.execute(StoredProcedure.java:137)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:122)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:207)
Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'bpa/prod'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:154)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:145)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	... 5 more
04-06-2019 10:33:21 ERROR143-Exception caught
com.tesco.card.payments.exceptions.BusinessException
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:136)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:207)
13-06-2019 10:31:26 ERROR143-Exception caught
com.tesco.card.payments.exceptions.BusinessException
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.doEnroll(CardPaymentsDAOImpl.java:136)
	at com.tesco.card.payments.dao.impl.CardPaymentsDAOImpl.main(CardPaymentsDAOImpl.java:207)
